<?php

namespace PIDEVBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAnnonce($search)
{
    return $this->createQueryBuilder('e')
        ->where('UPPER(e.titre) LIKE UPPER(:search)')
        ->setParameter('search', '%'.$search.'%')
        ->getQuery()
        ->getResult();

}
}
