<?php

namespace PIDEVBundle\Repository;

/**
 * TypeWorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeWorkshopRepository extends \Doctrine\ORM\EntityRepository
{
}
